import { pgTable, text, timestamp, integer, boolean, jsonb, uniqueIndex, index } from "drizzle-orm/pg-core";
export const meetings = pgTable("meetings", { id: text("id").primaryKey(), title: text("title").notNull(), date: timestamp("date").notNull(), durationSeconds: integer("duration_seconds").notNull(), status: text("status").notNull(), videoUrl: text("video_url").notNull(), summaryTemplate: text("summary_template").notNull(), shareToken: text("share_token"), createdAt: timestamp("created_at").defaultNow().notNull() }, (t) => ({ shareTokenIdx: uniqueIndex("meetings_share_token_idx").on(t.shareToken) }));
export const speakers = pgTable("speakers", { id: text("id").primaryKey(), meetingId: text("meeting_id").notNull().references(() => meetings.id), name: text("name").notNull(), avatarUrl: text("avatar_url").notNull(), color: text("color").notNull() });
export const chapters = pgTable("chapters", { id: text("id").primaryKey(), meetingId: text("meeting_id").notNull().references(() => meetings.id), title: text("title").notNull(), startMs: integer("start_ms").notNull(), endMs: integer("end_ms").notNull(), order: integer("order").notNull() });
export const transcriptSegments = pgTable("transcript_segments", { id: text("id").primaryKey(), meetingId: text("meeting_id").notNull().references(() => meetings.id), speakerId: text("speaker_id").notNull().references(() => speakers.id), startMs: integer("start_ms").notNull(), endMs: integer("end_ms").notNull(), text: text("text").notNull(), chapterId: text("chapter_id") }, (t) => ({ byTime: index("transcript_meeting_start_idx").on(t.meetingId, t.startMs) }));
export const summaries = pgTable("summaries", { id: text("id").primaryKey(), meetingId: text("meeting_id").notNull().references(() => meetings.id), template: text("template").notNull(), contentJson: jsonb("content_json").notNull(), generatedAt: timestamp("generated_at").defaultNow().notNull() });
export const actionItems = pgTable("action_items", { id: text("id").primaryKey(), meetingId: text("meeting_id").notNull().references(() => meetings.id), text: text("text").notNull(), owner: text("owner").notNull(), dueDate: timestamp("due_date").notNull(), completed: boolean("completed").default(false).notNull(), sourceSegmentId: text("source_segment_id") }, (t) => ({ byDone: index("action_items_meeting_completed_idx").on(t.meetingId, t.completed) }));
export const highlights = pgTable("highlights", { id: text("id").primaryKey(), meetingId: text("meeting_id").notNull().references(() => meetings.id), startMs: integer("start_ms").notNull(), endMs: integer("end_ms").notNull(), title: text("title").notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), shareToken: text("share_token").notNull() }, (t) => ({ shareTokenIdx: uniqueIndex("highlights_share_token_idx").on(t.shareToken) }));
export const meetingAttendees = pgTable("meeting_attendees", { meetingId: text("meeting_id").notNull().references(() => meetings.id), speakerId: text("speaker_id").notNull().references(() => speakers.id) });
