import Link from "next/link";
import { ArrowUpRight, Check, FileText, Search, Sparkles, Play, CalendarDays } from "lucide-react";
import { getCurrentUser } from "@/lib/auth";

export default async function Home() {
  const user = await getCurrentUser();
  return <>
    <section className="landing-hero">
      <div className="hero-copy"><span className="pill"><Sparkles size={14}/> A little less note-taking. A lot more clarity.</span><h1>Be in the meeting.<br/><em>Keep every insight.</em></h1><p className="hero-subhead">Give your conversations a place to live. Review recordings, find the decisions that matter, and turn the next steps into action.</p><div className="toolbar"><Link className="button primary" href={user ? "/meetings" : "/sign-up"}>{user ? "Go to workspace" : "Create your workspace"}<ArrowUpRight size={18}/></Link><Link className="button" href="/demo"><Play size={15}/> Explore the demo</Link></div><p className="hero-note">Your recordings. Searchable notes. One calm workspace.</p></div>
      <div className="product-preview"><div className="preview-top"><span className="preview-dots">&#9679; &#9679; &#9679;</span><span>Fathom / Meeting recap</span><span className="badge ready">Ready to review</span></div><div className="preview-body"><div className="preview-recording"><div className="toolbar"><span className="badge">Sample meeting</span><span className="muted">32:18</span></div><div className="participant-grid">{["JL", "AK", "MR", "ST"].map((name,i)=><div className={`participant participant-${i}`} key={name}><span>{name}</span></div>)}</div><div className="preview-timeline"/><div className="toolbar"><Play size={13}/><span className="muted">12:42 / 32:18</span></div><h3>Monday product sync</h3><p className="muted">Product team &middot; 4 participants</p></div><div className="preview-summary"><span className="eyebrow"><Sparkles size={14}/> THE TAKEAWAYS</span><h3>Good conversations.<br/>Clear next steps.</h3><p className="muted">The team aligned on a simpler onboarding flow and the next release priorities.</p><div className="preview-task"><Check size={16}/> Finalize the onboarding flow</div><div className="preview-task"><Check size={16}/> Share the launch checklist</div><div className="preview-quote">&ldquo;Let&apos;s make the first five minutes feel effortless.&rdquo;<small>Jamie &middot; 12:42</small></div></div></div></div>
    </section>
    <div className="workflow-strip"><span>FROM CONVERSATION TO CLARITY</span><span><CalendarDays size={18}/> Connect your calendar</span><span><Play size={18}/> Add a recording</span><span><Sparkles size={18}/> Find your next steps</span></div>
    <section className="feature-section" id="features"><p className="eyebrow">LESS BUSYWORK, MORE FOLLOW-THROUGH</p><h2>Everything after the meeting.<br/>Already in one place.</h2><div className="feature-grid">{[{Icon:FileText,title:"Pick up the whole story",text:"Review summaries alongside the recording. Jump from a transcript line to the exact moment it happened.",label:"01 / REVIEW"},{Icon:Check,title:"Make the next step clear",text:"Keep action items out of forgotten notes. Track what is open, in progress, and done across your meetings.",label:"02 / ACT"},{Icon:Search,title:"Find the moment that matters",text:"Search conversations and share a focused recap with the people who need it.",label:"03 / REMEMBER"}].map(({Icon,title,text,label})=><article className="feature-card" key={label}><Icon size={25}/><span className="feature-label">{label}</span><h3>{title}</h3><p className="muted">{text}</p><Link href="/demo">See it in the demo <ArrowUpRight size={15}/></Link></article>)}</div></section>
    <section className="landing-cta"><Sparkles size={28}/><h2>Your next meeting deserves<br/>a better follow-up.</h2><Link className="button primary" href={user ? "/meetings" : "/sign-up"}>Get started<ArrowUpRight size={18}/></Link></section>
  </>;
}
