import Link from "next/link";
import { eq } from "drizzle-orm";
import { Calendar, ShieldCheck } from "lucide-react";
import { CalendarControls } from "@/components/calendar/CalendarControls";
import { requireUser } from "@/lib/auth";
import { getDb } from "@/lib/db/client";
import * as schema from "@/lib/db/schema";

const integrations = ["Google Meet", "Zoom", "Teams", "Slack", "HubSpot"];

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ google?: string }> }) {
  const { google } = await searchParams;
  const notices: Record<string, string> = { connected: "Google Calendar connected and synced. Your upcoming meetings are ready on the dashboard.", sync_error: "Calendar connected, but the first sync failed. Try Sync calendar below.", denied: "Calendar access was cancelled. You can connect again when ready.", invalid_state: "The connection request expired. Please try connecting again.", error: "Calendar connection failed. Please reconnect and try again." };
  const user = await requireUser();
  const [connection] = await getDb().select({ email: schema.googleConnections.email, lastSyncedAt: schema.googleConnections.lastSyncedAt, error: schema.googleConnections.error }).from(schema.googleConnections).where(eq(schema.googleConnections.userId, user.id));
  return <>{google && notices[google] ? <p className="card" role="status">{notices[google]}</p> : null}<div className="page-head"><div><p className="eyebrow">Settings</p><h1>Integrations</h1><p className="muted">Connect your calendar, set up recording, and return here to manage your account.</p></div></div><section className="card" style={{marginBottom:18}}><div className="toolbar"><ShieldCheck color="var(--cyan)"/><h2>Account</h2></div><p className="muted">Signed in as {user.email}</p><span className="badge ready">Authenticated</span></section><section id="calendar" className="card" style={{marginBottom:18}}><div className="toolbar"><Calendar color="var(--violet)"/><h2>Google Calendar</h2></div><p className="muted">{connection ? `Connected as ${connection.email}` : "Read-only Calendar access finds Google Meet events. Recording still requires you to press Record in the desktop app."}</p>{connection?.lastSyncedAt ? <p className="muted">Last sync {connection.lastSyncedAt.toLocaleString()}</p> : null}{connection?.error ? <p className="muted">{connection.error}</p> : null}<CalendarControls connected={Boolean(connection)} /></section><section id="recording" className="card recording-setup"><p className="eyebrow">RECORDING SETUP</p><h2>Capture your first meeting</h2><p className="muted">This clone uses the Fathom Capture desktop app. It starts recording only when you press Record.</p><ol className="recording-instructions"><li><strong>Open Fathom Capture on your computer.</strong><p>If it is not installed, ask the workspace owner for the desktop app. You can upload an existing recording below instead.</p></li><li><strong>Pair it with your workspace.</strong><p>Connect your calendar above, then choose New agent token. In Fathom Capture, enter this website's address as the Backend URL, paste the token, and click Refresh meetings.</p></li><li><strong>Join your call and start recording.</strong><p>Choose your meeting, select its screen or window and audio source, then press Record. Let participants know you are recording.</p></li><li><strong>Stop recording to save your meeting.</strong><p>Keep the desktop app open while it uploads. Return to My meetings and open the recording once it is ready.</p></li></ol><div className="toolbar"><Link className="button primary" href="/meetings">Go to My meetings</Link><Link className="button" href="/upload">Upload an existing recording</Link></div></section><div className="grid cards">{integrations.map((name) => <section className="card" key={name}><div className="toolbar"><Calendar color="var(--muted)"/><h2>{name}</h2></div><span className="badge">{name === "Google Meet" ? "Available through Google Calendar" : "Coming soon"}</span></section>)}</div></>;
}
